authentication/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import LoginView, RegisterView, logout_request, profile, UpdateProfileView

urlpatterns = [
    path('login_user', LoginView.as_view(), name='login_user'),
    path('register', RegisterView.as_view(), name='register'),
    path('logout', logout_request, name='logout'),
    path('profile', profile, name='profile'),
    path('update', UpdateProfileView.as_view(), name='update')
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('account/', include(('authentication.urls',
         'authentication'), namespace='authentication')),
    path('features/', include(('features.urls', 'features'), namespace='features'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Goal(models.Model):
    calorie = models.IntegerField()
    plan = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.calorie}'


class FoodItem(models.Model):
    name = models.CharField(max_length=30)
    non_veg = models.BooleanField(default=False, blank=True)
    calorie = models.IntegerField()

    def __str__(self):
        return f"{self.name} - {self.calorie}"


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='profile', null=True)
    avatar = models.ImageField(
        default='avatars/default.jpg', upload_to='avatars', blank=True)
    weight = models.DecimalField(
        max_digits=5, decimal_places=2, blank=True, null=True)
    height = models.DecimalField(
        max_digits=5, decimal_places=2, blank=True, null=True)
    bmi = models.DecimalField(
        max_digits=5, decimal_places=2, blank=True, null=True)
    non_veg = models.BooleanField(default=False)
    calorie_goal = models.ForeignKey(
        Goal, on_delete=models.SET_NULL, null=True, blank=True)

    def get_total_calorie(self):
        foods = self.consumed.all()
        total = 0
        for food in foods:
            total += food.food_id.calorie
        return total

    def __str__(self):
        return f'{self.user.username}'


class Consumed(models.Model):
    food_id = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    consumed_by = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='consumed')

    def get_name(self):
        return self.food_id.name

    def get_calorie(self):
        return self.food_id.calorie

    def __str__(self):
        return f"{self.food_id.name} -{self.consumed_by.user.username}"

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from .models import Profile


def validate_email(value):
    u = User.objects.filter(email=value)
    if u.exists():
        raise ValidationError('Email already exists')


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ("username", "password")
        labels = {
            'username': ('Username'),
            'password': ('Password'),
        }


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True, validators=[validate_email])

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        labels = {
            'username': 'Username',
            'email': 'Email',
            'password1': 'Password',
            'password2': 'Confirm Password'
        }

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar', 'weight', 'height', 'bmi', 'non_veg')

authentication/views.py
from django.shortcuts import render, reverse
from django.views import View
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from io import BytesIO
from django.core.files import File
from PIL import Image
from django.core.files.uploadedfile import InMemoryUploadedFile
from .forms import LoginForm, RegisterForm, UpdateProfileForm
from .models import Profile
# Create your views here.


class LoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('home'))
        form = LoginForm()
        return render(request, 'authentication/login.html', {
            'form': form,
            'title': 'Login'
        })

    def post(self, request):
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f'Your are now logged in as {username}')
                print('login successfull')
                return HttpResponseRedirect(reverse('home'))
        else:
            messages.warning(request, 'Invalid Credentials')

        return render(request, 'authentication/login.html', {
            'form': form,
            'title': 'Login'
        })


class RegisterView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('home'))
        form = RegisterForm()
        return render(request, 'authentication/register.html', {
            'form': form,
            'title': 'Register'
        })

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            u1 = form.save()
            Profile.objects.create(user=u1)
            messages.success(request, "User created!!")
            return HttpResponseRedirect(reverse('authentication:login_user'))
        else:
            messages.warning(request, 'Invalid Data')

        return render(request, 'authentication/register.html', {
            'form': form,
            'title': 'Register'
        })

@login_required
def profile(request):
    return render(request, 'authentication/profile.html', {
        'title': 'Profile'
    })


class UpdateProfileView(View):
    def get(self, request):
        p = Profile.objects.get(user=request.user)
        form = UpdateProfileForm(instance=p)
        return render(request, 'authentication/update_profile.html', {
            'form': form,
            'title': 'Update'
        })

    def post(self, request):
        p = Profile.objects.get(user=request.user)

        files = request.FILES
        img = files.get('avatar')
        if img:
            i = Image.open(img)
            i = i.convert('RGB')
            thumb_io = BytesIO()
            i.save(thumb_io, format='JPEG', qualtiy=80)
            inmemory = InMemoryUploadedFile(
                thumb_io, None, f'{p.user.username}.jpeg', 'image/jpeg', thumb_io.tell(), None)
        form = UpdateProfileForm(request.POST, instance=p)
        if form.is_valid():
            updated_p = form.save()
            if img:
                updated_p.avatar = inmemory
                updated_p.save()
            messages.success(request, "Updated successfully")
            return HttpResponseRedirect(reverse('authentication:profile'))
        else:
            messages.error(request, 'Invalid Data')
        return render(request, 'authentication/update_profile.html', {
            'form': form,
            'title': 'Update'
        })


@login_required
def logout_request(request):
    logout(request)
    messages.info(request,'Bye Bye see you soon')
    return HttpResponseRedirect(reverse('home'))

authentication/templates/authentication/login.html
{% extends 'base.html' %} {% block title %} {{title}} {% endblock title %}
<!---->
{%block navbar %} {% include 'navbar.html' %} {% endblock navbar %} 
<!---->
{% block content %}
<div class="container mt-4">
 <h2>Please Login</h2>
</div>
  <div class="form-container m-2 w-100">
    <form method="POST">
      {% csrf_token %} {{form.non_field_errors}}
      <div class="form-group">
        {{form.username.errors1}} {{form.username.label_tag}} {{form.username}}
      </div>
      <div class="form-group">
        {{form.password.errors}} {{form.password.label_tag}} {{form.password}}
      </div>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
{% endblock content %}

authentication/templates/authentication/profile.html
{% extends 'base.html' %} {% block title %} {{title}} {% endblock title %}
<!---->
{%block navbar %} {% include 'navbar.html' %} {% endblock navbar %}
<!---->
{% block content %}
<div class="container d-flex justify-content-center">
  {% if user.profile.avatar %}
  <img
    class="img-thumbnail"
    src="{{user.profile.avatar.url}}"
    alt=""
    style="height: 200px; width: 200px"
  />
  {% else %}
  <img
    class="img-thumbnail"
    src="media/avatars/default.jpg"
    alt=""
    style="height: 200px; width: 200px"
  />
  {% endif %}
</div>
<div class="container m-2 w-100 text-center">
  <p>Name : {{user.username}}</p>
  <p>Weight : {{user.profile.weight}}</p>
  <p>Height : {{user.profile.height}}</p>
  <p>Weight : {{user.profile.bmi}}</p>
  <p>Non Veg :{{user.profile.non_veg}}</p>
  <p>Goal :{{user.profile.calorie_goal}}</p>
  <button type="button" class="btn btn-outline-dark">
    <a href="{%url 'authentication:update'  %}">Update Profile</a>
  </button>
</div>
{% endblock content %}

authentication/templates/authentication/register.html
{% extends 'base.html' %}
{% block title %}
{{title}}
{% endblock title %}
{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}
{% block content %}
<div class="container mt-4">
 <h2>Please Login</h2>
</div>
  <div class="form-container m-2 w-100">
    <form method="POST">
      {% csrf_token %} {{form.non_field_errors}}
      <div class="form-group">
    {{form.username.errors}}
    {{form.username.label_tag}}
    {{form.username}}
      </div>
      <div class="form-group">
    {{form.email.errors}}
    {{form.email.label_tag}}
    {{form.email}}
      </div>
      <div class="form-group">
    {{form.password1.errors}}
    {{form.password1.label_tag}}
    {{form.password1}}
      </div>
      <div class="form-group">
    {{form.password2.errors}}
    {{form.password2.label_tag}}
    {{form.password2}}
      </div>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
{% endblock content %}

authentication/templates/authentication/update_profile.html
{% extends 'base.html' %} {% block title %} {{title}} {% endblock title %}
<!---->
{% block navbar %} {% include 'navbar.html' %} {% endblock navbar %}
<!---->
{% block content %}
<div class="container d-flex justify-content-center">
  {% if user.profile.avatar %}
  <img
    class="img-thumbnail"
    src="{{user.profile.avatar.url}}"
    style="height: 200px; width: 200px"
    alt=""
  />
  {% else %}
  <img
    class="img-thumbnail"
    src="media/avatars/default.jpg"
    style="height: 200px; width: 200px"
    alt=""
  />
  {% endif %}
</div>
<div class="form-container m-2 w-100 text-center">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %} {{form.non_field_errors}}
    <div class="form-group">
      {{form.avatar.errors1}} {{form.avatar.label_tag}} {{form.avatar}}
    </div>
    <div class="form-group">
      {{form.weight.errors}} {{form.weight.label_tag}} {{form.weight}}
    </div>
    <div class="form-group">
      {{form.height.errors}} {{form.height.label_tag}} {{form.height}}
    </div>
    <div class="form-group">
      {{form.bmi.errors}} {{form.bmi.label_tag}} {{form.bmi}}
    </div>
    <div class="form-group">
      {{form.non_veg.errors}} {{form.non_veg.label_tag}} {{form.non_veg}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}