config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('account/', include(('authentication.urls',
         'authentication'), namespace='authentication')),
    path('features/', include(('features.urls', 'features'), namespace='features'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

features/urls.py
from django.urls import path
from .views import calorie_intake, calorie_goals, remove
urlpatterns = [
    path('intake', calorie_intake, name='intake'),
    path('goals', calorie_goals, name='goals'),
    path('remove/<int:id>', remove, name='remove')
]

features/models.py
from django.db import models

# Create your models here.

features/forms.py
from django import forms
from authentication.models import FoodItem, Goal


class VegForm(forms.Form):
    foods = FoodItem.objects.filter(non_veg=False)
    food_choices = ((food.id, food.name)for food in foods)
    food_choice = forms.ChoiceField(choices=food_choices, required=True)


class NonVegForm(forms.Form):
    foods = FoodItem.objects.all()
    food_choices = ((food.id, food.name)for food in foods)
    food_choice = forms.ChoiceField(choices=food_choices, required=True)


class CalorieForm(forms.Form):
    goals = Goal.objects.all()
    goal_choices = ((goal.id, goal.calorie) for goal in goals)
    goal_choice = forms.ChoiceField(choices=goal_choices, required=True)

features/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.views import View
from django.contrib import messages
from .forms import VegForm, NonVegForm, CalorieForm
import json
import threading
from authentication.models import Consumed, FoodItem, Goal
import time
# Create your views here.


@login_required
def calorie_intake(request):
    u = request.user
    consumed_list = u.profile.consumed
    if request.method == 'POST':
        if u.profile.non_veg:
            form = NonVegForm(request.POST)
        else:
            form = VegForm(request.POST)
        if form.is_valid():
            food_id = form.cleaned_data['food_choice']
            food_obj = FoodItem.objects.get(id=food_id)
            Consumed.objects.create(food_id=food_obj, consumed_by=u.profile)
            messages.success(request, f'you consumed {food_obj.name}')
        else:
            messages.error(request, 'Invalid')
    else:
        if u.profile.non_veg:
            form = NonVegForm()
        else:
            form = VegForm()
    return render(request, 'features/calorie_intake.html', {
        'form': form,
        'title': 'Intake',
        'consumed': consumed_list.all(),
    })


@login_required
def remove(request, id):
    c = Consumed.objects.get(id=id)
    if c:
        c.delete()
    return HttpResponseRedirect(reverse('features:intake'))


@login_required
def calorie_goals(request):
    p = request.user.profile
    table = None
    if p.calorie_goal:
        plan_path = p.calorie_goal.plan
        with open(plan_path, 'r') as f:
            table = json.loads(f.read())
        if p.non_veg:
            table = table[0]['non_veg']
        else:
            table = table[0]['veg']
    if request.method == "POST":
        form = CalorieForm(request.POST)
        if form.is_valid():
            goal_obj = Goal.objects.get(id=form.cleaned_data['goal_choice'])
            p.calorie_goal = goal_obj
            p.save()
            messages.success(
                request, f'Your update goal is now {goal_obj.calorie}')
            return HttpResponseRedirect(reverse('features:goals'))
    else:
        form = CalorieForm()
    return render(request, 'features/calorie_goals.html', {
        'form': form,
        'title': 'Goal',
        'table': table
    })

features/templates/features/calorie_goals.html
{% extends 'base.html' %} {% block title %} {{title}} {% endblock title %}
<!---->
{% block navbar %} {% include 'navbar.html' %} {% endblock navbar %}
<!---->
{% block content %}
<div class="container mt-5 d-flex flex-column justify-content-between">
  <div class="'container text-center">
    {% if user.profile.calorie_goal %}
    <h2>Your Calorie Goals is : {{user.profile.calorie_goal}}</h2>
    {% else %}
    <h2>You have no Goal set</h2>
    {% endif %}
  </div>
  <div class="container text-center">
    <form class="d-inline-flex" method="POST">
      {% csrf_token %}
      <div class="form-group">{{form}}</div>
      <button type="submit" class="btn btn-secondary btn-sm">Change</button>
    </form>
  </div>
</div>
<div class="container mt-5 d-flex flex-column">
  <div class="container text-center">
    <h3>Your plan diet</h3>
  </div>
  <div class="container">
      {% for row in table %}
    <ul class="list-group">
      <li
        class="list-group-item d-flex justify-content-between align-items-center"
      >
        <span class="badge badge-primary badge-pill">{{row.type}}</span>
        <span class="badge badge-primary badge-pill">{{row.quantity}}</span>
      </li>
      {% for ing in row.ingredients %}
      <li class="badge badge-primary badge-pill"></li>
        <p>{{ing}}</p>
      </li>
      {% endfor %}
    </ul>
    {% endfor %}
  </div>
</div>
{% endblock content %}

features/templates/features/calorie_intake.html
{% extends 'base.html' %} {% block title %} {{title}} {% endblock title %}
<!---->
{%block navbar %} {% include 'navbar.html' %} {% endblock navbar %}
<!---->
{% block content %}
<div class="container mt-5 d-flex flex-column">
  <div class="container text-center">
    <h2>Total Calorie Consumed : {{user.profile.get_total_calorie}}</h2>
    <form method="POST">
      {% csrf_token %} {{form}}
      <button type="submit">Eat</button>
    </form>
  </div>
  <div class="container text-center">
    <ul class="list-group">
      {% for food in consumed %}
      <li
        class="list-group-item d-flex justify-content-between align-items-center"
      >
        <span class="badge badge-primary badge">{{food.get_name}}</span>
        <span class=""><b>-------------------</b></span>
        <span class="badge badge-primary badge"
          >{{food.get_calorie}} Calorie</span
        >
        <form action="{% url 'features:remove' food.id %}" method="POST">
          {% csrf_token %}
          <button type="submit">Remove</button>
        </form>
        {% endfor %}
      </li>
    </ul>
  </div>
</div>
{% endblock content %}