authentication/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import LoginView, RegisterView, logout_request, profile, UpdateProfileView

urlpatterns = [
    path('login_user', LoginView.as_view(), name='login_user'),
    path('register', RegisterView.as_view(), name='register'),
    path('logout', logout_request, name='logout'),
    path('profile', profile, name='profile'),
    path('update', UpdateProfileView.as_view(), name='update')
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('account/', include(('authentication.urls',
         'authentication'), namespace='authentication')),
    path('features/', include(('features.urls', 'features'), namespace='features'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

features/urls.py
from django.urls import path
from .views import calorie_intake, calorie_goals, remove
urlpatterns = [
    path('intake', calorie_intake, name='intake'),
    path('goals', calorie_goals, name='goals'),
    path('remove/<int:id>', remove, name='remove')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <title>Health - {% block title %}{% endblock %}</title>
  </head>
  <style>
    .errorlist {
      color: red;
    }
    body {
      height: 100vh;
    }
    .item {
      background-color: gray;
      width: 100%;
      height: 100%;
      text-align: center;
    }
  </style>
  <body>
    {% block navbar %}{% endblock navbar %}
    <!---->
    {% if messages %} {% for message in messages %}
    <div
      class="alert alert-{{message.tags}} alert-dismissible fade show"
      role="alert"
    >
      <strong>Holy guacamole!</strong>{{message}}
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-label="Close"
      >
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %} {% endif %}
    <div
      class="container mx-auto w-100 h-100 d-flex flex-column align-item-center"
    >
      {% block content %} {%endblock content %}
    </div>
    <!---->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>
    <script>
      $('.alert').alert()
    </script>
  </body>
</html>

templates/navbar.html
{% comment %}
<nav>
  <a href="{% url 'home' %}">Home</a>
  <a href="{% url 'features:intake' %}">Calorie Intake</a>
  <a href="{% url 'features:goals' %}">Calorie Goals</a>
  {% if user.is_authenticated %}
  <a href="{% url 'authentication:profile' %}">{{user.username}}</a>
  <a href="{% url 'authentication:logout' %}">Logout</a>
  {% else %}
  <a href="{% url 'authentication:login'%}">Login</a>
  <a href="{% url 'authentication:register' %}">Register</a>
  {% endif %} {% endcomment %} {% comment %}
</nav>
{% endcomment %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a
    class="navbar-brand p-2 mr-2 bg-dark text-light rounded border border-primary"
    href="{% url 'home' %}"
    >Health Tracker</a
  >
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarText"
    aria-controls="navbarText"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a
          class="nav-link p-2 mr-2 bg-info text-light rounded border border-primary"
          href="{% url 'features:intake' %}"
          >Calorie Intake<span class="sr-only">(current)</span></a
        >
      </li>
      <li class="nav-item">
        <a
          class="nav-link p-2 mr-2 bg-info text-light rounded border border-primary"
          href="{% url 'features:goals' %}"
          >Calorie Goals</a
        >
      </li>
    </ul>
    <span class="navbar-link">
      {% if user.is_authenticated %}
      <a
        class="p-2 mr-2 bg-info text-light rounded border border-primary"
        href="{% url 'authentication:profile' %}"
        >{{user.username}}</a
      >
      <a
        class="p-2 mr-2 bg-info text-light rounded border border-primary"
        href="{% url 'authentication:logout' %}"
        >Logout</a
      >
      {% else %}
      <a
        class="p-2 mr-2 bg-info text-light rounded border border-primary"
        class="mr-2"
        href="{% url 'authentication:login_user' %}"
        >Login</a
      >
      <a
        class="p-2 mr-2 bg-info text-light rounded border border-primary"
        href="{% url 'authentication:register' %}"
        >Register</a
      >
      {% endif %}
    </span>
  </div>
</nav>